server {
    listen 80;
    server_name baby.kalinka-work.lqy.ch;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name baby.kalinka-work.lqy.ch;

    location / {
        include "snippets/proxy.conf";
        # The app runs in a container on plain HTTP; nginx terminates TLS.
        proxy_pass http://localhost:7881;
    }
}
